blueprint:
  name: Garage Door Departure (Distance + Location)
  description: >
    Close the garage door when a tracked vehicle leaves based on distance sensor
    readings and location handoffs.
  domain: automation
  input:
    distance_sensor:
      name: Distance sensor
      selector:
        entity:
          domain: sensor
    location_sensor:
      name: Location sensor
      description: Sensor that exposes `last_source`, `offline`, and distance metadata.
      selector:
        entity:
          domain: sensor
    control_boolean:
      name: Trigger guard boolean
      description: Helper that indicates the garage should close once the vehicle departs.
      selector:
        entity:
          domain: input_boolean
    garage_cover:
      name: Garage door
      selector:
        entity:
          domain: cover
    paired_arrival_automation:
      name: Paired arrival automation
      description: Automation to consult for cooldown/current checks.
      selector:
        entity:
          domain: automation
    log_label:
      name: Log label
      default: Vehicle
      selector:
        text:
          multiline: false
    garage_source_label:
      name: Garage source label
      default: Garage
      selector:
        text:
          multiline: false
    driveway_source_label:
      name: Driveway source label
      default: Driveway
      selector:
        text:
          multiline: false
    front_deck_source_label:
      name: Front deck source label
      default: Front Deck
      selector:
        text:
          multiline: false
    garage_state_name:
      name: Garage state name
      description: Expected state reported by the location sensor while inside the garage.
      default: garage
      selector:
        text:
          multiline: false
    offline_attribute:
      name: Offline attribute name
      default: offline
      selector:
        text:
          multiline: false
    garage_depart_threshold:
      name: Garage departure distance threshold (ft)
      default: 25
      selector:
        number:
          min: 1
          max: 200
          step: 1
          unit_of_measurement: ft
    far_threshold:
      name: Far distance threshold (ft)
      default: 50
      selector:
        number:
          min: 1
          max: 200
          step: 1
          unit_of_measurement: ft
    cooldown_seconds:
      name: Cooldown after arrival (seconds)
      default: 15
      selector:
        number:
          min: 0
          max: 600
          step: 1
          unit_of_measurement: s
    away_device_tracker_ids:
      name: Device tracker IDs to mark away
      description: >
        Optional list of `dev_id` values (one per line) that should be set to
        `not_home` when the garage closes.
      default: ""
      selector:
        text:
          multiline: true
    away_device_tracker_location_name:
      name: Device tracker departure location name
      default: not_home
      selector:
        text:
          multiline: false
mode: single
max_exceeded: silent
variables:
  distance_sensor: !input distance_sensor
  location_sensor: !input location_sensor
  control_boolean: !input control_boolean
  garage_cover: !input garage_cover
  paired_arrival: !input paired_arrival_automation
  log_label: !input log_label
  garage_source_label: !input garage_source_label
  driveway_source_label: !input driveway_source_label
  front_deck_source_label: !input front_deck_source_label
  garage_state_name: !input garage_state_name
  offline_attribute: !input offline_attribute
  garage_depart_threshold: !input garage_depart_threshold
  far_threshold: !input far_threshold
  cooldown_seconds: !input cooldown_seconds
  away_tracker_ids: !input away_device_tracker_ids
trigger:
  - platform: numeric_state
    entity_id: !input distance_sensor
    above: !input garage_depart_threshold
    for:
      seconds: 1
    id: garage_distance
  - platform: state
    entity_id: !input location_sensor
    to: !input driveway_source_label
    id: garage_to_driveway
  - platform: numeric_state
    entity_id: !input distance_sensor
    above: !input far_threshold
    for:
      seconds: 2
    id: driveway_far
  - platform: numeric_state
    entity_id: !input distance_sensor
    above: !input far_threshold
    for:
      seconds: 2
    id: front_deck_far
condition:
  - condition: template
    value_template: >
      {% set paired = paired_arrival %}
      {% if paired in ('', none) %}
        true
      {% else %}
        {% set last_trigger = state_attr(paired, 'last_triggered') %}
        {{ last_trigger is none or (as_timestamp(now()) - as_timestamp(last_trigger or 0)) > cooldown_seconds }}
      {% endif %}
  - condition: template
    value_template: >
      {% set paired = paired_arrival %}
      {% if paired in ('', none) %}
        true
      {% else %}
        {% set current = state_attr(paired, 'current') %}
        {{ current is none or current == 0 }}
      {% endif %}
  - condition: state
    entity_id: !input garage_cover
    state: "open"
  - condition: template
    value_template: >
      {% set distance = states(distance_sensor) | float(0) %}
      {% set last_source = state_attr(location_sensor, 'last_source') or '' %}
      {% if trigger.id == 'garage_distance' %}
        {{ garage_source_label in last_source }}
      {% elif trigger.id == 'garage_to_driveway' %}
        {% set from_state = trigger.from_state.state if trigger.from_state is not none else '' %}
        {% set last_distance = trigger.to_state.attributes.last_distance | default(distance, true) if trigger.to_state is not none else distance %}
        {{ from_state == garage_state_name and (last_distance | float(0)) <= garage_depart_threshold }}
      {% elif trigger.id == 'driveway_far' %}
        {{ driveway_source_label in last_source and distance > far_threshold }}
      {% elif trigger.id == 'front_deck_far' %}
        {{ front_deck_source_label in last_source and distance > far_threshold }}
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% set offline = state_attr(location_sensor, offline_attribute) %}
      {{ offline is not sameas true }}
action:
  - variables:
      tracker_ids: >
        {% set raw = away_tracker_ids | default('', true) %}
        {% if raw %}
          {{ raw.split() }}
        {% else %}
          []
        {% endif %}
  - service: logbook.log
    data:
      name: "{{ log_label }}"
      entity_id: !input location_sensor
      message: >
        {% set distance = (states(distance_sensor) | float(0)) | round(1) %}
        {% set source = state_attr(location_sensor, 'last_source') | default('unknown') %}
        {% if trigger.id == 'garage_to_driveway' %}
          departure via driveway handoff at {{ distance }}病t (source: {{ source }})
        {% elif trigger.id == 'garage_distance' %}
          departure via garage at {{ distance }}病t (source: {{ source }})
        {% elif trigger.id == 'driveway_far' %}
          departure via driveway range at {{ distance }}病t (source: {{ source }})
        {% else %}
          departure via front deck at {{ distance }}病t (source: {{ source }})
        {% endif %}
  - service: input_boolean.turn_off
    target:
      entity_id: !input control_boolean
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ tracker_ids | length > 0 }}"
        sequence:
          - repeat:
              for_each: "{{ tracker_ids }}"
              sequence:
                - service: device_tracker.see
                  data:
                    dev_id: "{{ repeat.item }}"
                    location_name: !input away_device_tracker_location_name
  - service: cover.close_cover
    target:
      entity_id: !input garage_cover
